version: "3"
services:

  api-gateway-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-gateway-web
    image: sca-api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - api-gateway-db
    environment:
    - PORT=8080
    - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
  
  api-gateway-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-security
         - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      
#docker system prune //limpa o cache
#SPRING_PROFILES_ACTIVE=test docker-compose up --build
#docker ps -a (imagens já criadas)
#docker build -t api-gateway-web  .
#docker run -p 8080:8080 -d <nome da imagem>
#docker stop <nome da imagem>
#docker rm <nome da imagem>
#docker ps (imagens ativas)