version: "3"
services:
  api-gateway-db:
    image: postgres:latest
    ports:
      - 5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sca-security
    networks:
      - sca-api-gateway-network
  api-gateway-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-gateway-web
    image: sca-api-gateway
    ports:
      #As portas abaixo serão ignoradas pelo heroku, que obriga utilizar a 
      #porta que ele envia via variável de ambiente:$PORT
      #Essa porta deve ser configurada apenas no arquivo application.properties 
      #da aplicação, ou seja, em nenhum Dockerfile ou docker-compose
      - '8080:8080'
    depends_on:
      - api-gateway-db
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
    networks:
      - sca-api-gateway-network
networks:
    sca-api-gateway-network:
        driver: bridge 