delete from users_roles;
delete from users;
delete from roles;
INSERT INTO users (user_id, user_name, password, email) VALUES (1, 'admin', '$2a$10$O/lbct/ufcCfg1OqVKswcehy4ESdchsR.Ih8ddyV1dE5EXWXlV262', 'admin@gmail.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (2, 'breno', '$2a$10$6Xke/4jI3EBvKgaSRLWc8.BMY2oiaZOTh/DMI.bjdL7lbPy/wZi1K', 'teste@gmail.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (3, 'monte', '$2a$10$lE9hK6MN.50rOWCIzg5ZEeCEGSUfCAVwx2.vAyCWj761.UzmqkBJS', 'mmonte@yahoo.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (4, 'novak.djokovic', '$2a$10$1XVzlMtF01aOLSy0JNciEOJYs7XunXfmJMFmfyDhduq/shmeAfuX2', 'novak@gmail.com');
INSERT INTO roles (role_id, name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (role_id, name) VALUES (2, 'ROLE_OPERADOR');
INSERT INTO roles (role_id, name) VALUES (3, 'ROLE_TERCEIRIZADO');
INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (1, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (1, 3);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 2);