delete from users_roles;
delete from users;
delete from roles;
INSERT INTO users (user_id, user_name, password, email) VALUES (1, 'ADMIN', '$2a$10$5G8zCENFxEA3F.y5P5xcV.ivgZzEuSxO9eqMCp1ouoIODnCL/h64y', 'admin@gmail.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (2, 'BRENO PEREIRA', 'c84ff789436a5d7f0bf8504bb6b69d83', 'teste@gmail.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (3, 'MARISA MONTE', 'eacd672d120794985928af70c63da849', 'mmonte@yahoo.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (4, 'TIAGO SILVA', 'c79924ec82f57b59c26cf5c1e2b8b6ca', 'tiagosilva1985@gmail.com');
INSERT INTO users (user_id, user_name, password, email) VALUES (5, 'NOVAK DJOKOVIC', 'b2375cf689675824504b2df74434037e', 'novak@gmail.com');
INSERT INTO roles (role_id, name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO roles (role_id, name) VALUES (2, 'ROLE_OPERADOR');
INSERT INTO roles (role_id, name) VALUES (3, 'ROLE_TERCEIRIZADO');
INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (1, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (1, 3);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 2);